-- Generated by db/generate-subcategories.mjs -- do not edit by hand.
--
-- Adds the second level of the category tree, which the original seed
-- omitted, and repoints products at the subcategory they belong to so the
-- storefront can offer subcategory filters from the database.

INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active)
VALUES ('shirts-tshirts', 'mens-fashion', 'Shirts & T-Shirts', 'shirts-tshirts', NULL, 'https://images.unsplash.com/photo-1516257984-b1b4d707412e?auto=format&fit=crop&w=200&q=70', 0, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active)
VALUES ('jackets', 'mens-fashion', 'Jackets', 'jackets', NULL, 'https://images.unsplash.com/photo-1516257984-b1b4d707412e?auto=format&fit=crop&w=200&q=70', 1, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active)
VALUES ('mens-footwear', 'mens-fashion', 'Footwear', 'mens-footwear', NULL, 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=200&q=70', 2, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active)
VALUES ('panjabi', 'mens-fashion', 'Panjabi', 'panjabi', NULL, 'https://images.unsplash.com/photo-1591561954557-26941169b49e?auto=format&fit=crop&w=200&q=70', 3, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active)
VALUES ('dresses', 'womens-fashion', 'Dresses', 'dresses', NULL, 'https://images.unsplash.com/photo-1591369822096-ffd140ec948f?auto=format&fit=crop&w=200&q=70', 0, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active)
VALUES ('kurti-salwar', 'womens-fashion', 'Kurti & Salwar', 'kurti-salwar', NULL, 'https://images.unsplash.com/photo-1591369822096-ffd140ec948f?auto=format&fit=crop&w=200&q=70', 1, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active)
VALUES ('sarees', 'womens-fashion', 'Sarees', 'sarees', NULL, 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=200&q=70', 2, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active)
VALUES ('womens-footwear', 'womens-fashion', 'Footwear', 'womens-footwear', NULL, 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=200&q=70', 3, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active)
VALUES ('wallets-belts', 'mens-accessories', 'Wallets & Belts', 'wallets-belts', NULL, 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&w=200&q=70', 0, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active)
VALUES ('mens-watches', 'mens-accessories', 'Watches', 'mens-watches', NULL, 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=200&q=70', 1, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active)
VALUES ('bags-backpacks', 'mens-accessories', 'Bags & Backpacks', 'bags-backpacks', NULL, 'https://images.unsplash.com/photo-1591561954557-26941169b49e?auto=format&fit=crop&w=200&q=70', 2, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active)
VALUES ('bangles-jewellery', 'womens-accessories', 'Bangles & Jewellery', 'bangles-jewellery', NULL, 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=200&q=70', 0, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active)
VALUES ('handbags', 'womens-accessories', 'Handbags', 'handbags', NULL, 'https://images.unsplash.com/photo-1591561954557-26941169b49e?auto=format&fit=crop&w=200&q=70', 1, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active)
VALUES ('womens-watches', 'womens-accessories', 'Watches', 'womens-watches', NULL, 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=200&q=70', 2, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active)
VALUES ('baby-clothing', 'baby-products', 'Baby Clothing', 'baby-clothing', NULL, 'https://images.unsplash.com/photo-1522771930-78848d9293e8?auto=format&fit=crop&w=200&q=70', 0, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active)
VALUES ('baby-care', 'baby-products', 'Baby Care', 'baby-care', NULL, 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=200&q=70', 1, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active)
VALUES ('toys', 'baby-products', 'Toys', 'toys', NULL, 'https://images.unsplash.com/photo-1522771930-78848d9293e8?auto=format&fit=crop&w=200&q=70', 2, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active)
VALUES ('skincare', 'health-beauty', 'Skin Care', 'skincare', NULL, 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=200&q=70', 0, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active)
VALUES ('haircare', 'health-beauty', 'Hair Care', 'haircare', NULL, 'https://images.unsplash.com/photo-1526947425960-945c6e72858f?auto=format&fit=crop&w=200&q=70', 1, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active)
VALUES ('makeup', 'health-beauty', 'Makeup', 'makeup', NULL, 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=200&q=70', 2, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active)
VALUES ('wellness', 'health-beauty', 'Wellness', 'wellness', NULL, 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=200&q=70', 3, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active)
VALUES ('audio', 'electronics', 'Audio', 'audio', NULL, 'https://images.unsplash.com/photo-1560243563-062bfc001d68?auto=format&fit=crop&w=200&q=70', 0, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active)
VALUES ('wearables', 'electronics', 'Wearables', 'wearables', NULL, 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=200&q=70', 1, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active)
VALUES ('mobile-accessories', 'electronics', 'Mobile Accessories', 'mobile-accessories', NULL, 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=200&q=70', 2, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active)
VALUES ('home-appliances', 'electronics', 'Home Appliances', 'home-appliances', NULL, 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=200&q=70', 3, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active)
VALUES ('body-care', 'body-bath', 'Body Care', 'body-care', NULL, 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=200&q=70', 0, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active)
VALUES ('bath-essentials', 'body-bath', 'Bath Essentials', 'bath-essentials', NULL, 'https://images.unsplash.com/photo-1526947425960-945c6e72858f?auto=format&fit=crop&w=200&q=70', 1, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active)
VALUES ('fragrance', 'body-bath', 'Fragrance', 'fragrance', NULL, 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=200&q=70', 2, 1);

-- Repoint products at their subcategory. Products without one keep the
-- department they already had.
UPDATE products SET category_id = 'wearables' WHERE id = 'smart-watch-7';
UPDATE products SET category_id = 'mens-footwear' WHERE id = 'white-sneaker';
UPDATE products SET category_id = 'audio' WHERE id = 'wireless-headphones';
UPDATE products SET category_id = 'skincare' WHERE id = 'glow-serum';
UPDATE products SET category_id = 'jackets' WHERE id = 'mens-denim-jacket';
UPDATE products SET category_id = 'dresses' WHERE id = 'womens-floral-dress';
UPDATE products SET category_id = 'wallets-belts' WHERE id = 'leather-wallet-belt-combo';
UPDATE products SET category_id = 'bangles-jewellery' WHERE id = 'gold-plated-bangle-set';
UPDATE products SET category_id = 'baby-clothing' WHERE id = 'baby-cotton-romper-set';
UPDATE products SET category_id = 'body-care' WHERE id = 'organic-body-lotion';
UPDATE products SET category_id = 'audio' WHERE id = 'bluetooth-portable-speaker';
UPDATE products SET category_id = 'skincare' WHERE id = 'vitamin-c-brightening-cream';
UPDATE products SET category_id = 'wearables' WHERE id = 'digital-fitness-tracker';
UPDATE products SET category_id = 'shirts-tshirts' WHERE id = 'mens-cotton-casual-shirt';
UPDATE products SET category_id = 'shirts-tshirts' WHERE id = 'mens-polo-tshirt';
UPDATE products SET category_id = 'panjabi' WHERE id = 'mens-embroidered-panjabi';
UPDATE products SET category_id = 'kurti-salwar' WHERE id = 'womens-cotton-kurti-set';
UPDATE products SET category_id = 'sarees' WHERE id = 'jamdani-cotton-saree';
UPDATE products SET category_id = 'womens-footwear' WHERE id = 'womens-flat-sandal';
UPDATE products SET category_id = 'mens-watches' WHERE id = 'mens-leather-watch';
UPDATE products SET category_id = 'bags-backpacks' WHERE id = 'laptop-backpack';
UPDATE products SET category_id = 'handbags' WHERE id = 'womens-structured-handbag';
UPDATE products SET category_id = 'womens-watches' WHERE id = 'womens-rose-gold-watch';
UPDATE products SET category_id = 'baby-care' WHERE id = 'baby-gentle-care-lotion';
UPDATE products SET category_id = 'toys' WHERE id = 'plush-toy-set';
UPDATE products SET category_id = 'haircare' WHERE id = 'argan-hair-oil';
UPDATE products SET category_id = 'makeup' WHERE id = 'matte-lipstick-set';
UPDATE products SET category_id = 'wellness' WHERE id = 'daily-multivitamin';
UPDATE products SET category_id = 'mobile-accessories' WHERE id = 'fast-power-bank';
UPDATE products SET category_id = 'mobile-accessories' WHERE id = 'gan-fast-charger';
UPDATE products SET category_id = 'home-appliances' WHERE id = 'electric-kettle';
UPDATE products SET category_id = 'bath-essentials' WHERE id = 'herbal-shower-gel-duo';
UPDATE products SET category_id = 'fragrance' WHERE id = 'oud-musk-body-mist';
