-- GENERATED FILE -- do not edit by hand.
-- Regenerate with: node db/generate-seed.mjs
-- Seeds the initial Zupona catalog (categories, brands, products,
-- images, variants, feature badges) plus baseline platform settings.
-- Every statement is INSERT OR IGNORE: safe to re-run, never clobbers
-- rows that have since been edited through the admin tooling.

-- Categories: top-level departments plus their subcategories
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active) VALUES ('mens-fashion', NULL, 'Men''s Fashion', 'mens-fashion', 'Style for every you', 'https://images.unsplash.com/photo-1516257984-b1b4d707412e?auto=format&fit=crop&w=640&q=80', 0, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active) VALUES ('shirts-tshirts', 'mens-fashion', 'Shirts & T-Shirts', 'shirts-tshirts', NULL, 'https://images.unsplash.com/photo-1516257984-b1b4d707412e?auto=format&fit=crop&w=640&q=80', 0, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active) VALUES ('jackets', 'mens-fashion', 'Jackets', 'jackets', NULL, 'https://images.unsplash.com/photo-1516257984-b1b4d707412e?auto=format&fit=crop&w=640&q=80', 1, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active) VALUES ('mens-footwear', 'mens-fashion', 'Footwear', 'mens-footwear', NULL, 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=640&q=80', 2, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active) VALUES ('panjabi', 'mens-fashion', 'Panjabi', 'panjabi', NULL, 'https://images.unsplash.com/photo-1591561954557-26941169b49e?auto=format&fit=crop&w=640&q=80', 3, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active) VALUES ('womens-fashion', NULL, 'Women''s Fashion', 'womens-fashion', 'Trendy & Traditional', 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=640&q=80', 1, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active) VALUES ('dresses', 'womens-fashion', 'Dresses', 'dresses', NULL, 'https://images.unsplash.com/photo-1591369822096-ffd140ec948f?auto=format&fit=crop&w=640&q=80', 0, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active) VALUES ('kurti-salwar', 'womens-fashion', 'Kurti & Salwar', 'kurti-salwar', NULL, 'https://images.unsplash.com/photo-1591369822096-ffd140ec948f?auto=format&fit=crop&w=640&q=80', 1, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active) VALUES ('sarees', 'womens-fashion', 'Sarees', 'sarees', NULL, 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=640&q=80', 2, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active) VALUES ('womens-footwear', 'womens-fashion', 'Footwear', 'womens-footwear', NULL, 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=640&q=80', 3, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active) VALUES ('mens-accessories', NULL, 'Men''s Accessories', 'mens-accessories', 'Upgrade Your Style', 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&w=640&q=80', 2, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active) VALUES ('wallets-belts', 'mens-accessories', 'Wallets & Belts', 'wallets-belts', NULL, 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&w=640&q=80', 0, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active) VALUES ('mens-watches', 'mens-accessories', 'Watches', 'mens-watches', NULL, 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=640&q=80', 1, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active) VALUES ('bags-backpacks', 'mens-accessories', 'Bags & Backpacks', 'bags-backpacks', NULL, 'https://images.unsplash.com/photo-1591561954557-26941169b49e?auto=format&fit=crop&w=640&q=80', 2, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active) VALUES ('womens-accessories', NULL, 'Women''s Accessories', 'womens-accessories', 'Elegance in Details', 'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?auto=format&fit=crop&w=640&q=80', 3, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active) VALUES ('bangles-jewellery', 'womens-accessories', 'Bangles & Jewellery', 'bangles-jewellery', NULL, 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=640&q=80', 0, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active) VALUES ('handbags', 'womens-accessories', 'Handbags', 'handbags', NULL, 'https://images.unsplash.com/photo-1591561954557-26941169b49e?auto=format&fit=crop&w=640&q=80', 1, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active) VALUES ('womens-watches', 'womens-accessories', 'Watches', 'womens-watches', NULL, 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=640&q=80', 2, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active) VALUES ('baby-products', NULL, 'Baby Products', 'baby-products', 'Everything for Little Ones', 'https://images.unsplash.com/photo-1522771930-78848d9293e8?auto=format&fit=crop&w=640&q=80', 4, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active) VALUES ('baby-clothing', 'baby-products', 'Baby Clothing', 'baby-clothing', NULL, 'https://images.unsplash.com/photo-1522771930-78848d9293e8?auto=format&fit=crop&w=640&q=80', 0, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active) VALUES ('baby-care', 'baby-products', 'Baby Care', 'baby-care', NULL, 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=640&q=80', 1, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active) VALUES ('toys', 'baby-products', 'Toys', 'toys', NULL, 'https://images.unsplash.com/photo-1522771930-78848d9293e8?auto=format&fit=crop&w=640&q=80', 2, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active) VALUES ('health-beauty', NULL, 'Health & Beauty', 'health-beauty', 'Care Today, Glow Tomorrow', 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=640&q=80', 5, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active) VALUES ('skincare', 'health-beauty', 'Skin Care', 'skincare', NULL, 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=640&q=80', 0, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active) VALUES ('haircare', 'health-beauty', 'Hair Care', 'haircare', NULL, 'https://images.unsplash.com/photo-1526947425960-945c6e72858f?auto=format&fit=crop&w=640&q=80', 1, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active) VALUES ('makeup', 'health-beauty', 'Makeup', 'makeup', NULL, 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=640&q=80', 2, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active) VALUES ('wellness', 'health-beauty', 'Wellness', 'wellness', NULL, 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=640&q=80', 3, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active) VALUES ('electronics', NULL, 'Electronics', 'electronics', 'Smart Choices, Smarter Life', 'https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&w=640&q=80', 6, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active) VALUES ('audio', 'electronics', 'Audio', 'audio', NULL, 'https://images.unsplash.com/photo-1560243563-062bfc001d68?auto=format&fit=crop&w=640&q=80', 0, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active) VALUES ('wearables', 'electronics', 'Wearables', 'wearables', NULL, 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=640&q=80', 1, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active) VALUES ('mobile-accessories', 'electronics', 'Mobile Accessories', 'mobile-accessories', NULL, 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=640&q=80', 2, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active) VALUES ('home-appliances', 'electronics', 'Home Appliances', 'home-appliances', NULL, 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=640&q=80', 3, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active) VALUES ('body-bath', NULL, 'Body & Bath', 'body-bath', 'Refresh, Rejuvenate, Repeat.', 'https://images.unsplash.com/photo-1526947425960-945c6e72858f?auto=format&fit=crop&w=640&q=80', 7, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active) VALUES ('body-care', 'body-bath', 'Body Care', 'body-care', NULL, 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=640&q=80', 0, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active) VALUES ('bath-essentials', 'body-bath', 'Bath Essentials', 'bath-essentials', NULL, 'https://images.unsplash.com/photo-1526947425960-945c6e72858f?auto=format&fit=crop&w=640&q=80', 1, 1);
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, subtitle, image_url, sort_order, is_active) VALUES ('fragrance', 'body-bath', 'Fragrance', 'fragrance', NULL, 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=640&q=80', 2, 1);

-- Brands, derived from the distinct brand names in the static catalog
INSERT OR IGNORE INTO brands (id, name, slug) VALUES ('brand-glow-naturally', 'GLOW NATURALLY', 'glow-naturally');
INSERT OR IGNORE INTO brands (id, name, slug) VALUES ('brand-zupona', 'ZUPONA', 'zupona');
INSERT OR IGNORE INTO brands (id, name, slug) VALUES ('brand-zupona-audio', 'ZUPONA AUDIO', 'zupona-audio');
INSERT OR IGNORE INTO brands (id, name, slug) VALUES ('brand-zupona-kids', 'ZUPONA KIDS', 'zupona-kids');
INSERT OR IGNORE INTO brands (id, name, slug) VALUES ('brand-zupona-sport', 'ZUPONA SPORT', 'zupona-sport');

-- Products. seller_id stays NULL: these are platform-owned (first-party)
-- listings. Marketplace sellers set seller_id on their own products.
INSERT OR IGNORE INTO products (id, seller_id, category_id, brand_id, name, slug, sku, hero_headline, hero_subtitle, status, price, old_price, currency, is_featured, is_best_seller, rating_avg, rating_count) VALUES ('smart-watch-7', NULL, 'wearables', 'brand-zupona', 'Z-Smart Watch Pro Series 7', 'smart-watch-7', 'ZUP-SMART-WATCH-7', 'Smart On Your Wrist', 'Track Every Moment', 'active', 2999, 3999, 'BDT', 1, 1, 4.8, 120);
INSERT OR IGNORE INTO product_images (id, product_id, url, sort_order, is_primary) VALUES ('smart-watch-7-img-1', 'smart-watch-7', 'https://images.unsplash.com/photo-1544117519-31a4b719223d?auto=format&fit=crop&w=1200&q=85', 0, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('smart-watch-7-v1', 'smart-watch-7', 'ZUP-SMART-WATCH-7-1', 'Color', 'Black & Gold', 'linear-gradient(135deg,#1c1c1c,#caa24a)', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('smart-watch-7-v2', 'smart-watch-7', 'ZUP-SMART-WATCH-7-2', 'Color', 'Silver & Blue', 'linear-gradient(135deg,#c7cdd4,#3b6fd6)', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('smart-watch-7-v3', 'smart-watch-7', 'ZUP-SMART-WATCH-7-3', 'Color', 'All Black', '#1c1c1c', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('smart-watch-7-v4', 'smart-watch-7', 'ZUP-SMART-WATCH-7-4', 'Color', 'Rose Gold', 'linear-gradient(135deg,#e8b7a0,#b76e56)', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('smart-watch-7-f1', 'smart-watch-7', 'Droplets', 'Water Resistant', 0);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('smart-watch-7-f2', 'smart-watch-7', 'Timer', 'Fitness Tracking', 1);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('smart-watch-7-f3', 'smart-watch-7', 'ShieldCheck', 'Durable Build', 2);

INSERT OR IGNORE INTO products (id, seller_id, category_id, brand_id, name, slug, sku, hero_headline, hero_subtitle, status, price, old_price, currency, is_featured, is_best_seller, rating_avg, rating_count) VALUES ('white-sneaker', NULL, 'mens-footwear', 'brand-zupona-sport', 'Classic White Sneaker', 'white-sneaker', 'ZUP-WHITE-SNEAKER', 'Everyday Comfort', 'Built to Move', 'active', 1699, 2099, 'BDT', 1, 1, 4.7, 88);
INSERT OR IGNORE INTO product_images (id, product_id, url, sort_order, is_primary) VALUES ('white-sneaker-img-1', 'white-sneaker', 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=1200&q=85', 0, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('white-sneaker-v1', 'white-sneaker', 'ZUP-WHITE-SNEAKER-1', 'Color', 'Pure White', '#f5f5f4', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('white-sneaker-v2', 'white-sneaker', 'ZUP-WHITE-SNEAKER-2', 'Color', 'Black & White', 'linear-gradient(135deg,#1c1c1c,#f5f5f4)', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('white-sneaker-v3', 'white-sneaker', 'ZUP-WHITE-SNEAKER-3', 'Color', 'Grey', '#9ca3af', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('white-sneaker-f1', 'white-sneaker', 'ShieldCheck', 'Durable Sole', 0);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('white-sneaker-f2', 'white-sneaker', 'Sparkles', 'Breathable Mesh', 1);

INSERT OR IGNORE INTO products (id, seller_id, category_id, brand_id, name, slug, sku, hero_headline, hero_subtitle, status, price, old_price, currency, is_featured, is_best_seller, rating_avg, rating_count) VALUES ('wireless-headphones', NULL, 'audio', 'brand-zupona-audio', 'Latest Wireless Headphone', 'wireless-headphones', 'ZUP-WIRELESS-HEADPHONES', 'Immersive Sound', 'Wire Free', 'active', 1899, 2499, 'BDT', 0, 1, 4.7, 210);
INSERT OR IGNORE INTO product_images (id, product_id, url, sort_order, is_primary) VALUES ('wireless-headphones-img-1', 'wireless-headphones', 'https://images.unsplash.com/photo-1560243563-062bfc001d68?auto=format&fit=crop&w=1200&q=85', 0, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('wireless-headphones-v1', 'wireless-headphones', 'ZUP-WIRELESS-HEADPHONES-1', 'Color', 'Matte Black', '#1c1c1c', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('wireless-headphones-v2', 'wireless-headphones', 'ZUP-WIRELESS-HEADPHONES-2', 'Color', 'Pearl White', '#f5f5f4', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('wireless-headphones-f1', 'wireless-headphones', 'Volume2', 'Active Noise Cancel', 0);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('wireless-headphones-f2', 'wireless-headphones', 'BatteryFull', '30Hr Battery', 1);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('wireless-headphones-f3', 'wireless-headphones', 'ShieldCheck', 'Sweat Resistant', 2);

INSERT OR IGNORE INTO products (id, seller_id, category_id, brand_id, name, slug, sku, hero_headline, hero_subtitle, status, price, old_price, currency, is_featured, is_best_seller, rating_avg, rating_count) VALUES ('glow-serum', NULL, 'skincare', 'brand-glow-naturally', 'Glow Naturally Face Serum', 'glow-serum', 'ZUP-GLOW-SERUM', 'Radiant Skin', 'Naturally', 'active', 899, 1199, 'BDT', 0, 0, 4.4, 76);
INSERT OR IGNORE INTO product_images (id, product_id, url, sort_order, is_primary) VALUES ('glow-serum-img-1', 'glow-serum', 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=1200&q=85', 0, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('glow-serum-v1', 'glow-serum', 'ZUP-GLOW-SERUM-1', NULL, NULL, NULL, NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('glow-serum-f1', 'glow-serum', 'Droplets', 'Deep Hydration', 0);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('glow-serum-f2', 'glow-serum', 'Sparkles', 'Glow Boost', 1);

INSERT OR IGNORE INTO products (id, seller_id, category_id, brand_id, name, slug, sku, hero_headline, hero_subtitle, status, price, old_price, currency, is_featured, is_best_seller, rating_avg, rating_count) VALUES ('mens-denim-jacket', NULL, 'jackets', 'brand-zupona', 'Men''s Classic Denim Jacket', 'mens-denim-jacket', 'ZUP-MENS-DENIM-JACKET', 'Timeless Style', 'Layer It Up', 'active', 1799, 2399, 'BDT', 0, 1, 4.5, 63);
INSERT OR IGNORE INTO product_images (id, product_id, url, sort_order, is_primary) VALUES ('mens-denim-jacket-img-1', 'mens-denim-jacket', 'https://images.unsplash.com/photo-1516257984-b1b4d707412e?auto=format&fit=crop&w=1200&q=85', 0, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('mens-denim-jacket-v1', 'mens-denim-jacket', 'ZUP-MENS-DENIM-JACKET-1', 'Color', 'Indigo Blue', '#3b5998', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('mens-denim-jacket-v2', 'mens-denim-jacket', 'ZUP-MENS-DENIM-JACKET-2', 'Color', 'Washed Grey', '#9ca3af', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('mens-denim-jacket-v3', 'mens-denim-jacket', 'ZUP-MENS-DENIM-JACKET-3', 'Color', 'Jet Black', '#1c1c1c', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('mens-denim-jacket-f1', 'mens-denim-jacket', 'Shirt', 'Classic Fit', 0);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('mens-denim-jacket-f2', 'mens-denim-jacket', 'ShieldCheck', 'Durable Denim', 1);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('mens-denim-jacket-f3', 'mens-denim-jacket', 'Wind', 'Breathable', 2);

INSERT OR IGNORE INTO products (id, seller_id, category_id, brand_id, name, slug, sku, hero_headline, hero_subtitle, status, price, old_price, currency, is_featured, is_best_seller, rating_avg, rating_count) VALUES ('womens-floral-dress', NULL, 'dresses', 'brand-zupona', 'Women''s Floral Summer Dress', 'womens-floral-dress', 'ZUP-WOMENS-FLORAL-DRESS', 'Effortless Elegance', 'Made for Summer', 'active', 1499, 1999, 'BDT', 0, 0, 4.6, 142);
INSERT OR IGNORE INTO product_images (id, product_id, url, sort_order, is_primary) VALUES ('womens-floral-dress-img-1', 'womens-floral-dress', 'https://images.unsplash.com/photo-1591369822096-ffd140ec948f?auto=format&fit=crop&w=1200&q=85', 0, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('womens-floral-dress-v1', 'womens-floral-dress', 'ZUP-WOMENS-FLORAL-DRESS-1', 'Color', 'Floral Pink', '#e8a0b0', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('womens-floral-dress-v2', 'womens-floral-dress', 'ZUP-WOMENS-FLORAL-DRESS-2', 'Color', 'Sky Blue', '#a0c4e8', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('womens-floral-dress-f1', 'womens-floral-dress', 'Sparkles', 'Elegant Design', 0);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('womens-floral-dress-f2', 'womens-floral-dress', 'Wind', 'Lightweight Fabric', 1);

INSERT OR IGNORE INTO products (id, seller_id, category_id, brand_id, name, slug, sku, hero_headline, hero_subtitle, status, price, old_price, currency, is_featured, is_best_seller, rating_avg, rating_count) VALUES ('leather-wallet-belt-combo', NULL, 'wallets-belts', 'brand-zupona', 'Leather Wallet & Belt Combo', 'leather-wallet-belt-combo', 'ZUP-LEATHER-WALLET-BELT-COMBO', 'Everyday Essentials', 'Genuine Leather', 'active', 1299, 1699, 'BDT', 0, 0, 4.7, 89);
INSERT OR IGNORE INTO product_images (id, product_id, url, sort_order, is_primary) VALUES ('leather-wallet-belt-combo-img-1', 'leather-wallet-belt-combo', 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&w=1200&q=85', 0, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('leather-wallet-belt-combo-v1', 'leather-wallet-belt-combo', 'ZUP-LEATHER-WALLET-BELT-COMBO-1', 'Color', 'Classic Brown', '#6b4423', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('leather-wallet-belt-combo-v2', 'leather-wallet-belt-combo', 'ZUP-LEATHER-WALLET-BELT-COMBO-2', 'Color', 'Jet Black', '#1c1c1c', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('leather-wallet-belt-combo-f1', 'leather-wallet-belt-combo', 'ShieldCheck', 'Genuine Leather', 0);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('leather-wallet-belt-combo-f2', 'leather-wallet-belt-combo', 'Gem', 'Premium Finish', 1);

INSERT OR IGNORE INTO products (id, seller_id, category_id, brand_id, name, slug, sku, hero_headline, hero_subtitle, status, price, old_price, currency, is_featured, is_best_seller, rating_avg, rating_count) VALUES ('gold-plated-bangle-set', NULL, 'bangles-jewellery', 'brand-zupona', 'Traditional Gold-Plated Bangle Set', 'gold-plated-bangle-set', 'ZUP-GOLD-PLATED-BANGLE-SET', 'Traditional Charm', 'Wear It Proud', 'active', 999, 1499, 'BDT', 0, 1, 4.8, 156);
INSERT OR IGNORE INTO product_images (id, product_id, url, sort_order, is_primary) VALUES ('gold-plated-bangle-set-img-1', 'gold-plated-bangle-set', 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=1200&q=85', 0, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('gold-plated-bangle-set-v1', 'gold-plated-bangle-set', 'ZUP-GOLD-PLATED-BANGLE-SET-1', 'Color', 'Gold', 'linear-gradient(135deg,#f5d67a,#b8860b)', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('gold-plated-bangle-set-v2', 'gold-plated-bangle-set', 'ZUP-GOLD-PLATED-BANGLE-SET-2', 'Color', 'Rose Gold', 'linear-gradient(135deg,#e8b7a0,#b76e56)', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('gold-plated-bangle-set-f1', 'gold-plated-bangle-set', 'Gem', 'Gold Plated', 0);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('gold-plated-bangle-set-f2', 'gold-plated-bangle-set', 'Sparkles', 'Elegant Shine', 1);

INSERT OR IGNORE INTO products (id, seller_id, category_id, brand_id, name, slug, sku, hero_headline, hero_subtitle, status, price, old_price, currency, is_featured, is_best_seller, rating_avg, rating_count) VALUES ('baby-cotton-romper-set', NULL, 'baby-clothing', 'brand-zupona-kids', 'Baby Soft Cotton Romper Set', 'baby-cotton-romper-set', 'ZUP-BABY-COTTON-ROMPER-SET', 'Little Comfort', 'Soft on Skin', 'active', 599, 799, 'BDT', 0, 0, 4.9, 47);
INSERT OR IGNORE INTO product_images (id, product_id, url, sort_order, is_primary) VALUES ('baby-cotton-romper-set-img-1', 'baby-cotton-romper-set', 'https://images.unsplash.com/photo-1522771930-78848d9293e8?auto=format&fit=crop&w=1200&q=85', 0, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('baby-cotton-romper-set-v1', 'baby-cotton-romper-set', 'ZUP-BABY-COTTON-ROMPER-SET-1', 'Color', 'Baby Yellow', '#f5e6a0', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('baby-cotton-romper-set-v2', 'baby-cotton-romper-set', 'ZUP-BABY-COTTON-ROMPER-SET-2', 'Color', 'Mint Green', '#a0e8c4', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('baby-cotton-romper-set-f1', 'baby-cotton-romper-set', 'Baby', 'Skin Friendly', 0);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('baby-cotton-romper-set-f2', 'baby-cotton-romper-set', 'Droplets', 'Soft Cotton', 1);

INSERT OR IGNORE INTO products (id, seller_id, category_id, brand_id, name, slug, sku, hero_headline, hero_subtitle, status, price, old_price, currency, is_featured, is_best_seller, rating_avg, rating_count) VALUES ('organic-body-lotion', NULL, 'body-care', 'brand-glow-naturally', 'Organic Body Lotion', 'organic-body-lotion', 'ZUP-ORGANIC-BODY-LOTION', 'Nourish Naturally', 'All Day Softness', 'active', 549, 699, 'BDT', 0, 0, 4.3, 34);
INSERT OR IGNORE INTO product_images (id, product_id, url, sort_order, is_primary) VALUES ('organic-body-lotion-img-1', 'organic-body-lotion', 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=1200&q=85', 0, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('organic-body-lotion-v1', 'organic-body-lotion', 'ZUP-ORGANIC-BODY-LOTION-1', NULL, NULL, NULL, NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('organic-body-lotion-f1', 'organic-body-lotion', 'Droplets', 'Deep Moisture', 0);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('organic-body-lotion-f2', 'organic-body-lotion', 'Sparkles', 'Non-Greasy', 1);

INSERT OR IGNORE INTO products (id, seller_id, category_id, brand_id, name, slug, sku, hero_headline, hero_subtitle, status, price, old_price, currency, is_featured, is_best_seller, rating_avg, rating_count) VALUES ('bluetooth-portable-speaker', NULL, 'audio', 'brand-zupona-audio', 'Bluetooth Portable Speaker', 'bluetooth-portable-speaker', 'ZUP-BLUETOOTH-PORTABLE-SPEAKER', 'Sound On the Go', 'Big Bass, Small Size', 'active', 1199, 1599, 'BDT', 0, 1, 4.5, 118);
INSERT OR IGNORE INTO product_images (id, product_id, url, sort_order, is_primary) VALUES ('bluetooth-portable-speaker-img-1', 'bluetooth-portable-speaker', 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1200&q=85', 0, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('bluetooth-portable-speaker-v1', 'bluetooth-portable-speaker', 'ZUP-BLUETOOTH-PORTABLE-SPEAKER-1', 'Color', 'Matte Black', '#1c1c1c', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('bluetooth-portable-speaker-v2', 'bluetooth-portable-speaker', 'ZUP-BLUETOOTH-PORTABLE-SPEAKER-2', 'Color', 'Ocean Blue', '#3b6fd6', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('bluetooth-portable-speaker-f1', 'bluetooth-portable-speaker', 'Volume2', 'Rich Bass', 0);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('bluetooth-portable-speaker-f2', 'bluetooth-portable-speaker', 'BatteryFull', '12Hr Playtime', 1);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('bluetooth-portable-speaker-f3', 'bluetooth-portable-speaker', 'ShieldCheck', 'Water Resistant', 2);

INSERT OR IGNORE INTO products (id, seller_id, category_id, brand_id, name, slug, sku, hero_headline, hero_subtitle, status, price, old_price, currency, is_featured, is_best_seller, rating_avg, rating_count) VALUES ('vitamin-c-brightening-cream', NULL, 'skincare', 'brand-glow-naturally', 'Vitamin C Skin Brightening Cream', 'vitamin-c-brightening-cream', 'ZUP-VITAMIN-C-BRIGHTENING-CREAM', 'Brighter Skin', 'In Just Weeks', 'active', 749, 999, 'BDT', 0, 0, 4.4, 92);
INSERT OR IGNORE INTO product_images (id, product_id, url, sort_order, is_primary) VALUES ('vitamin-c-brightening-cream-img-1', 'vitamin-c-brightening-cream', 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=1200&q=85', 0, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('vitamin-c-brightening-cream-v1', 'vitamin-c-brightening-cream', 'ZUP-VITAMIN-C-BRIGHTENING-CREAM-1', NULL, NULL, NULL, NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('vitamin-c-brightening-cream-f1', 'vitamin-c-brightening-cream', 'Droplets', 'Hydrating', 0);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('vitamin-c-brightening-cream-f2', 'vitamin-c-brightening-cream', 'Sparkles', 'Brightening', 1);

INSERT OR IGNORE INTO products (id, seller_id, category_id, brand_id, name, slug, sku, hero_headline, hero_subtitle, status, price, old_price, currency, is_featured, is_best_seller, rating_avg, rating_count) VALUES ('digital-fitness-tracker', NULL, 'wearables', 'brand-zupona', 'Digital Fitness Tracker Band', 'digital-fitness-tracker', 'ZUP-DIGITAL-FITNESS-TRACKER', 'Track Your Health', 'Every Step Counts', 'active', 899, 1299, 'BDT', 0, 0, 4.2, 55);
INSERT OR IGNORE INTO product_images (id, product_id, url, sort_order, is_primary) VALUES ('digital-fitness-tracker-img-1', 'digital-fitness-tracker', 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=1200&q=85', 0, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('digital-fitness-tracker-v1', 'digital-fitness-tracker', 'ZUP-DIGITAL-FITNESS-TRACKER-1', 'Color', 'All Black', '#1c1c1c', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('digital-fitness-tracker-v2', 'digital-fitness-tracker', 'ZUP-DIGITAL-FITNESS-TRACKER-2', 'Color', 'Coral Pink', '#e8909f', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('digital-fitness-tracker-f1', 'digital-fitness-tracker', 'Watch', 'Slim Design', 0);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('digital-fitness-tracker-f2', 'digital-fitness-tracker', 'Timer', 'Sleep Tracking', 1);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('digital-fitness-tracker-f3', 'digital-fitness-tracker', 'BatteryFull', '7 Day Battery', 2);

INSERT OR IGNORE INTO products (id, seller_id, category_id, brand_id, name, slug, sku, hero_headline, hero_subtitle, status, price, old_price, currency, is_featured, is_best_seller, rating_avg, rating_count) VALUES ('mens-cotton-casual-shirt', NULL, 'shirts-tshirts', 'brand-zupona', 'Men''s Cotton Casual Shirt', 'mens-cotton-casual-shirt', 'ZUP-MENS-COTTON-CASUAL-SHIRT', 'Crisp All Day', 'Breathable Cotton', 'active', 1099, 1499, 'BDT', 0, 0, 4.4, 71);
INSERT OR IGNORE INTO product_images (id, product_id, url, sort_order, is_primary) VALUES ('mens-cotton-casual-shirt-img-1', 'mens-cotton-casual-shirt', 'https://images.unsplash.com/photo-1516257984-b1b4d707412e?auto=format&fit=crop&w=1200&q=85', 0, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('mens-cotton-casual-shirt-v1', 'mens-cotton-casual-shirt', 'ZUP-MENS-COTTON-CASUAL-SHIRT-1', 'Color', 'Sky Blue', '#a0c4e8', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('mens-cotton-casual-shirt-v2', 'mens-cotton-casual-shirt', 'ZUP-MENS-COTTON-CASUAL-SHIRT-2', 'Color', 'Off White', '#f5f5f4', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('mens-cotton-casual-shirt-v3', 'mens-cotton-casual-shirt', 'ZUP-MENS-COTTON-CASUAL-SHIRT-3', 'Color', 'Olive', '#6b7a52', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('mens-cotton-casual-shirt-f1', 'mens-cotton-casual-shirt', 'Shirt', 'Regular Fit', 0);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('mens-cotton-casual-shirt-f2', 'mens-cotton-casual-shirt', 'Wind', 'Breathable Cotton', 1);

INSERT OR IGNORE INTO products (id, seller_id, category_id, brand_id, name, slug, sku, hero_headline, hero_subtitle, status, price, old_price, currency, is_featured, is_best_seller, rating_avg, rating_count) VALUES ('mens-polo-tshirt', NULL, 'shirts-tshirts', 'brand-zupona-sport', 'Men''s Premium Polo T-Shirt', 'mens-polo-tshirt', 'ZUP-MENS-POLO-TSHIRT', 'Smart Casual', 'Everyday Polo', 'active', 849, 1099, 'BDT', 0, 0, 4.3, 58);
INSERT OR IGNORE INTO product_images (id, product_id, url, sort_order, is_primary) VALUES ('mens-polo-tshirt-img-1', 'mens-polo-tshirt', 'https://images.unsplash.com/photo-1516257984-b1b4d707412e?auto=format&fit=crop&w=1200&q=85', 0, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('mens-polo-tshirt-v1', 'mens-polo-tshirt', 'ZUP-MENS-POLO-TSHIRT-1', 'Color', 'Navy', '#1f3a5f', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('mens-polo-tshirt-v2', 'mens-polo-tshirt', 'ZUP-MENS-POLO-TSHIRT-2', 'Color', 'Maroon', '#7b2d3b', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('mens-polo-tshirt-f1', 'mens-polo-tshirt', 'Shirt', 'Pique Knit', 0);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('mens-polo-tshirt-f2', 'mens-polo-tshirt', 'Wind', 'Quick Dry', 1);

INSERT OR IGNORE INTO products (id, seller_id, category_id, brand_id, name, slug, sku, hero_headline, hero_subtitle, status, price, old_price, currency, is_featured, is_best_seller, rating_avg, rating_count) VALUES ('mens-embroidered-panjabi', NULL, 'panjabi', 'brand-zupona', 'Men''s Embroidered Panjabi', 'mens-embroidered-panjabi', 'ZUP-MENS-EMBROIDERED-PANJABI', 'Festive Ready', 'Hand Embroidered', 'active', 2199, 2999, 'BDT', 0, 1, 4.7, 134);
INSERT OR IGNORE INTO product_images (id, product_id, url, sort_order, is_primary) VALUES ('mens-embroidered-panjabi-img-1', 'mens-embroidered-panjabi', 'https://images.unsplash.com/photo-1591561954557-26941169b49e?auto=format&fit=crop&w=1200&q=85', 0, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('mens-embroidered-panjabi-v1', 'mens-embroidered-panjabi', 'ZUP-MENS-EMBROIDERED-PANJABI-1', 'Color', 'Cream', '#efe6d3', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('mens-embroidered-panjabi-v2', 'mens-embroidered-panjabi', 'ZUP-MENS-EMBROIDERED-PANJABI-2', 'Color', 'Deep Maroon', '#6b2438', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('mens-embroidered-panjabi-f1', 'mens-embroidered-panjabi', 'Gem', 'Hand Embroidery', 0);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('mens-embroidered-panjabi-f2', 'mens-embroidered-panjabi', 'Wind', 'Soft Cotton Blend', 1);

INSERT OR IGNORE INTO products (id, seller_id, category_id, brand_id, name, slug, sku, hero_headline, hero_subtitle, status, price, old_price, currency, is_featured, is_best_seller, rating_avg, rating_count) VALUES ('womens-cotton-kurti-set', NULL, 'kurti-salwar', 'brand-zupona', 'Women''s Cotton Kurti Set', 'womens-cotton-kurti-set', 'ZUP-WOMENS-COTTON-KURTI-SET', 'Comfort Daily', 'Three Piece Set', 'active', 1650, 2200, 'BDT', 0, 0, 4.5, 187);
INSERT OR IGNORE INTO product_images (id, product_id, url, sort_order, is_primary) VALUES ('womens-cotton-kurti-set-img-1', 'womens-cotton-kurti-set', 'https://images.unsplash.com/photo-1591369822096-ffd140ec948f?auto=format&fit=crop&w=1200&q=85', 0, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('womens-cotton-kurti-set-v1', 'womens-cotton-kurti-set', 'ZUP-WOMENS-COTTON-KURTI-SET-1', 'Color', 'Teal', '#2f7f7f', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('womens-cotton-kurti-set-v2', 'womens-cotton-kurti-set', 'ZUP-WOMENS-COTTON-KURTI-SET-2', 'Color', 'Mustard', '#d4a017', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('womens-cotton-kurti-set-f1', 'womens-cotton-kurti-set', 'Wind', 'Pure Cotton', 0);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('womens-cotton-kurti-set-f2', 'womens-cotton-kurti-set', 'Sparkles', 'Block Printed', 1);

INSERT OR IGNORE INTO products (id, seller_id, category_id, brand_id, name, slug, sku, hero_headline, hero_subtitle, status, price, old_price, currency, is_featured, is_best_seller, rating_avg, rating_count) VALUES ('jamdani-cotton-saree', NULL, 'sarees', 'brand-zupona', 'Jamdani Cotton Saree', 'jamdani-cotton-saree', 'ZUP-JAMDANI-COTTON-SAREE', 'Woven Heritage', 'Handloom Jamdani', 'active', 3499, 4999, 'BDT', 0, 1, 4.9, 96);
INSERT OR IGNORE INTO product_images (id, product_id, url, sort_order, is_primary) VALUES ('jamdani-cotton-saree-img-1', 'jamdani-cotton-saree', 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=1200&q=85', 0, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('jamdani-cotton-saree-v1', 'jamdani-cotton-saree', 'ZUP-JAMDANI-COTTON-SAREE-1', 'Color', 'Ivory & Red', 'linear-gradient(135deg,#f5efe0,#b03030)', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('jamdani-cotton-saree-v2', 'jamdani-cotton-saree', 'ZUP-JAMDANI-COTTON-SAREE-2', 'Color', 'Sea Green', '#2e8b74', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('jamdani-cotton-saree-f1', 'jamdani-cotton-saree', 'Gem', 'Handloom Woven', 0);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('jamdani-cotton-saree-f2', 'jamdani-cotton-saree', 'Wind', 'Breathable Cotton', 1);

INSERT OR IGNORE INTO products (id, seller_id, category_id, brand_id, name, slug, sku, hero_headline, hero_subtitle, status, price, old_price, currency, is_featured, is_best_seller, rating_avg, rating_count) VALUES ('womens-flat-sandal', NULL, 'womens-footwear', 'brand-zupona', 'Women''s Everyday Flat Sandal', 'womens-flat-sandal', 'ZUP-WOMENS-FLAT-SANDAL', 'Walk Easy', 'Cushioned Sole', 'active', 899, 1299, 'BDT', 0, 0, 4.2, 64);
INSERT OR IGNORE INTO product_images (id, product_id, url, sort_order, is_primary) VALUES ('womens-flat-sandal-img-1', 'womens-flat-sandal', 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=1200&q=85', 0, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('womens-flat-sandal-v1', 'womens-flat-sandal', 'ZUP-WOMENS-FLAT-SANDAL-1', 'Color', 'Tan', '#c19a6b', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('womens-flat-sandal-v2', 'womens-flat-sandal', 'ZUP-WOMENS-FLAT-SANDAL-2', 'Color', 'Black', '#1c1c1c', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('womens-flat-sandal-f1', 'womens-flat-sandal', 'ShieldCheck', 'Anti-Slip Sole', 0);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('womens-flat-sandal-f2', 'womens-flat-sandal', 'Sparkles', 'Soft Footbed', 1);

INSERT OR IGNORE INTO products (id, seller_id, category_id, brand_id, name, slug, sku, hero_headline, hero_subtitle, status, price, old_price, currency, is_featured, is_best_seller, rating_avg, rating_count) VALUES ('mens-leather-watch', NULL, 'mens-watches', 'brand-zupona', 'Men''s Classic Leather Watch', 'mens-leather-watch', 'ZUP-MENS-LEATHER-WATCH', 'Timeless On Wrist', 'Genuine Leather Strap', 'active', 1899, 2599, 'BDT', 0, 0, 4.6, 112);
INSERT OR IGNORE INTO product_images (id, product_id, url, sort_order, is_primary) VALUES ('mens-leather-watch-img-1', 'mens-leather-watch', 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=1200&q=85', 0, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('mens-leather-watch-v1', 'mens-leather-watch', 'ZUP-MENS-LEATHER-WATCH-1', 'Color', 'Brown & Gold', 'linear-gradient(135deg,#6b4423,#caa24a)', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('mens-leather-watch-v2', 'mens-leather-watch', 'ZUP-MENS-LEATHER-WATCH-2', 'Color', 'Black & Silver', 'linear-gradient(135deg,#1c1c1c,#c7cdd4)', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('mens-leather-watch-f1', 'mens-leather-watch', 'Watch', 'Quartz Movement', 0);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('mens-leather-watch-f2', 'mens-leather-watch', 'Droplets', 'Splash Resistant', 1);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('mens-leather-watch-f3', 'mens-leather-watch', 'ShieldCheck', 'Mineral Glass', 2);

INSERT OR IGNORE INTO products (id, seller_id, category_id, brand_id, name, slug, sku, hero_headline, hero_subtitle, status, price, old_price, currency, is_featured, is_best_seller, rating_avg, rating_count) VALUES ('laptop-backpack', NULL, 'bags-backpacks', 'brand-zupona', 'Water-Resistant Laptop Backpack', 'laptop-backpack', 'ZUP-LAPTOP-BACKPACK', 'Carry It All', 'Built for Commute', 'active', 1499, 2099, 'BDT', 0, 0, 4.5, 143);
INSERT OR IGNORE INTO product_images (id, product_id, url, sort_order, is_primary) VALUES ('laptop-backpack-img-1', 'laptop-backpack', 'https://images.unsplash.com/photo-1591561954557-26941169b49e?auto=format&fit=crop&w=1200&q=85', 0, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('laptop-backpack-v1', 'laptop-backpack', 'ZUP-LAPTOP-BACKPACK-1', 'Color', 'Charcoal', '#36393d', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('laptop-backpack-v2', 'laptop-backpack', 'ZUP-LAPTOP-BACKPACK-2', 'Color', 'Navy', '#1f3a5f', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('laptop-backpack-f1', 'laptop-backpack', 'Droplets', 'Water Resistant', 0);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('laptop-backpack-f2', 'laptop-backpack', 'Package', 'Fits 15.6 inch Laptop', 1);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('laptop-backpack-f3', 'laptop-backpack', 'ShieldCheck', 'Reinforced Straps', 2);

INSERT OR IGNORE INTO products (id, seller_id, category_id, brand_id, name, slug, sku, hero_headline, hero_subtitle, status, price, old_price, currency, is_featured, is_best_seller, rating_avg, rating_count) VALUES ('womens-structured-handbag', NULL, 'handbags', 'brand-zupona', 'Women''s Structured Handbag', 'womens-structured-handbag', 'ZUP-WOMENS-STRUCTURED-HANDBAG', 'Hold Your Day', 'Structured & Roomy', 'active', 1799, 2499, 'BDT', 0, 0, 4.6, 128);
INSERT OR IGNORE INTO product_images (id, product_id, url, sort_order, is_primary) VALUES ('womens-structured-handbag-img-1', 'womens-structured-handbag', 'https://images.unsplash.com/photo-1591561954557-26941169b49e?auto=format&fit=crop&w=1200&q=85', 0, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('womens-structured-handbag-v1', 'womens-structured-handbag', 'ZUP-WOMENS-STRUCTURED-HANDBAG-1', 'Color', 'Blush', '#e8b7a0', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('womens-structured-handbag-v2', 'womens-structured-handbag', 'ZUP-WOMENS-STRUCTURED-HANDBAG-2', 'Color', 'Jet Black', '#1c1c1c', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('womens-structured-handbag-f1', 'womens-structured-handbag', 'Gem', 'Premium Finish', 0);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('womens-structured-handbag-f2', 'womens-structured-handbag', 'Package', 'Three Compartments', 1);

INSERT OR IGNORE INTO products (id, seller_id, category_id, brand_id, name, slug, sku, hero_headline, hero_subtitle, status, price, old_price, currency, is_featured, is_best_seller, rating_avg, rating_count) VALUES ('womens-rose-gold-watch', NULL, 'womens-watches', 'brand-zupona', 'Women''s Slim Rose Gold Watch', 'womens-rose-gold-watch', 'ZUP-WOMENS-ROSE-GOLD-WATCH', 'Quietly Elegant', 'Slim Rose Gold', 'active', 1599, 2299, 'BDT', 0, 0, 4.4, 87);
INSERT OR IGNORE INTO product_images (id, product_id, url, sort_order, is_primary) VALUES ('womens-rose-gold-watch-img-1', 'womens-rose-gold-watch', 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=1200&q=85', 0, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('womens-rose-gold-watch-v1', 'womens-rose-gold-watch', 'ZUP-WOMENS-ROSE-GOLD-WATCH-1', 'Color', 'Rose Gold', 'linear-gradient(135deg,#e8b7a0,#b76e56)', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('womens-rose-gold-watch-v2', 'womens-rose-gold-watch', 'ZUP-WOMENS-ROSE-GOLD-WATCH-2', 'Color', 'Pearl White', '#f5f5f4', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('womens-rose-gold-watch-f1', 'womens-rose-gold-watch', 'Watch', 'Slim 7mm Case', 0);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('womens-rose-gold-watch-f2', 'womens-rose-gold-watch', 'Gem', 'Rose Gold Plated', 1);

INSERT OR IGNORE INTO products (id, seller_id, category_id, brand_id, name, slug, sku, hero_headline, hero_subtitle, status, price, old_price, currency, is_featured, is_best_seller, rating_avg, rating_count) VALUES ('baby-gentle-care-lotion', NULL, 'baby-care', 'brand-glow-naturally', 'Baby Gentle Care Lotion', 'baby-gentle-care-lotion', 'ZUP-BABY-GENTLE-CARE-LOTION', 'Gentle by Nature', 'Made for Newborns', 'active', 449, 599, 'BDT', 0, 0, 4.8, 152);
INSERT OR IGNORE INTO product_images (id, product_id, url, sort_order, is_primary) VALUES ('baby-gentle-care-lotion-img-1', 'baby-gentle-care-lotion', 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=1200&q=85', 0, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('baby-gentle-care-lotion-v1', 'baby-gentle-care-lotion', 'ZUP-BABY-GENTLE-CARE-LOTION-1', NULL, NULL, NULL, NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('baby-gentle-care-lotion-f1', 'baby-gentle-care-lotion', 'Baby', 'Newborn Safe', 0);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('baby-gentle-care-lotion-f2', 'baby-gentle-care-lotion', 'Droplets', '24Hr Moisture', 1);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('baby-gentle-care-lotion-f3', 'baby-gentle-care-lotion', 'Leaf', 'No Harsh Chemicals', 2);

INSERT OR IGNORE INTO products (id, seller_id, category_id, brand_id, name, slug, sku, hero_headline, hero_subtitle, status, price, old_price, currency, is_featured, is_best_seller, rating_avg, rating_count) VALUES ('plush-toy-set', NULL, 'toys', 'brand-zupona-kids', 'Soft Plush Toy Set', 'plush-toy-set', 'ZUP-PLUSH-TOY-SET', 'First Friends', 'Huggably Soft', 'active', 749, 999, 'BDT', 0, 0, 4.7, 68);
INSERT OR IGNORE INTO product_images (id, product_id, url, sort_order, is_primary) VALUES ('plush-toy-set-img-1', 'plush-toy-set', 'https://images.unsplash.com/photo-1522771930-78848d9293e8?auto=format&fit=crop&w=1200&q=85', 0, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('plush-toy-set-v1', 'plush-toy-set', 'ZUP-PLUSH-TOY-SET-1', NULL, NULL, NULL, NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('plush-toy-set-f1', 'plush-toy-set', 'Baby', 'Non-Toxic', 0);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('plush-toy-set-f2', 'plush-toy-set', 'Sparkles', 'Machine Washable', 1);

INSERT OR IGNORE INTO products (id, seller_id, category_id, brand_id, name, slug, sku, hero_headline, hero_subtitle, status, price, old_price, currency, is_featured, is_best_seller, rating_avg, rating_count) VALUES ('argan-hair-oil', NULL, 'haircare', 'brand-glow-naturally', 'Argan Hair Repair Oil', 'argan-hair-oil', 'ZUP-ARGAN-HAIR-OIL', 'Repair & Shine', 'Cold Pressed Argan', 'active', 649, 899, 'BDT', 0, 0, 4.5, 203);
INSERT OR IGNORE INTO product_images (id, product_id, url, sort_order, is_primary) VALUES ('argan-hair-oil-img-1', 'argan-hair-oil', 'https://images.unsplash.com/photo-1526947425960-945c6e72858f?auto=format&fit=crop&w=1200&q=85', 0, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('argan-hair-oil-v1', 'argan-hair-oil', 'ZUP-ARGAN-HAIR-OIL-1', NULL, NULL, NULL, NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('argan-hair-oil-f1', 'argan-hair-oil', 'Leaf', 'Cold Pressed', 0);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('argan-hair-oil-f2', 'argan-hair-oil', 'Droplets', 'Deep Nourish', 1);

INSERT OR IGNORE INTO products (id, seller_id, category_id, brand_id, name, slug, sku, hero_headline, hero_subtitle, status, price, old_price, currency, is_featured, is_best_seller, rating_avg, rating_count) VALUES ('matte-lipstick-set', NULL, 'makeup', 'brand-glow-naturally', 'Matte Liquid Lipstick Set', 'matte-lipstick-set', 'ZUP-MATTE-LIPSTICK-SET', 'Colour That Stays', '12 Hour Matte', 'active', 999, 1499, 'BDT', 0, 1, 4.6, 241);
INSERT OR IGNORE INTO product_images (id, product_id, url, sort_order, is_primary) VALUES ('matte-lipstick-set-img-1', 'matte-lipstick-set', 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=1200&q=85', 0, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('matte-lipstick-set-v1', 'matte-lipstick-set', 'ZUP-MATTE-LIPSTICK-SET-1', 'Color', 'Classic Red', '#b02a37', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('matte-lipstick-set-v2', 'matte-lipstick-set', 'ZUP-MATTE-LIPSTICK-SET-2', 'Color', 'Nude Rose', '#c98a80', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('matte-lipstick-set-v3', 'matte-lipstick-set', 'ZUP-MATTE-LIPSTICK-SET-3', 'Color', 'Deep Berry', '#6b2438', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('matte-lipstick-set-f1', 'matte-lipstick-set', 'Sparkles', '12Hr Wear', 0);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('matte-lipstick-set-f2', 'matte-lipstick-set', 'Droplets', 'Non-Drying', 1);

INSERT OR IGNORE INTO products (id, seller_id, category_id, brand_id, name, slug, sku, hero_headline, hero_subtitle, status, price, old_price, currency, is_featured, is_best_seller, rating_avg, rating_count) VALUES ('daily-multivitamin', NULL, 'wellness', 'brand-glow-naturally', 'Daily Multivitamin Complex', 'daily-multivitamin', 'ZUP-DAILY-MULTIVITAMIN', 'Everyday Strength', '60 Day Supply', 'active', 899, 1199, 'BDT', 0, 0, 4.3, 79);
INSERT OR IGNORE INTO product_images (id, product_id, url, sort_order, is_primary) VALUES ('daily-multivitamin-img-1', 'daily-multivitamin', 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=1200&q=85', 0, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('daily-multivitamin-v1', 'daily-multivitamin', 'ZUP-DAILY-MULTIVITAMIN-1', NULL, NULL, NULL, NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('daily-multivitamin-f1', 'daily-multivitamin', 'ShieldCheck', 'Lab Tested', 0);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('daily-multivitamin-f2', 'daily-multivitamin', 'Leaf', 'Vegetarian Capsule', 1);

INSERT OR IGNORE INTO products (id, seller_id, category_id, brand_id, name, slug, sku, hero_headline, hero_subtitle, status, price, old_price, currency, is_featured, is_best_seller, rating_avg, rating_count) VALUES ('fast-power-bank', NULL, 'mobile-accessories', 'brand-zupona', '20000mAh Fast Power Bank', 'fast-power-bank', 'ZUP-FAST-POWER-BANK', 'Never Run Out', '20000mAh Fast Charge', 'active', 2199, 2999, 'BDT', 0, 1, 4.6, 318);
INSERT OR IGNORE INTO product_images (id, product_id, url, sort_order, is_primary) VALUES ('fast-power-bank-img-1', 'fast-power-bank', 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1200&q=85', 0, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('fast-power-bank-v1', 'fast-power-bank', 'ZUP-FAST-POWER-BANK-1', 'Color', 'Matte Black', '#1c1c1c', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('fast-power-bank-v2', 'fast-power-bank', 'ZUP-FAST-POWER-BANK-2', 'Color', 'Silver', '#c7cdd4', NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('fast-power-bank-f1', 'fast-power-bank', 'BatteryFull', '20000mAh', 0);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('fast-power-bank-f2', 'fast-power-bank', 'Zap', '22.5W Fast Charge', 1);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('fast-power-bank-f3', 'fast-power-bank', 'ShieldCheck', 'Overcharge Safe', 2);

INSERT OR IGNORE INTO products (id, seller_id, category_id, brand_id, name, slug, sku, hero_headline, hero_subtitle, status, price, old_price, currency, is_featured, is_best_seller, rating_avg, rating_count) VALUES ('gan-fast-charger', NULL, 'mobile-accessories', 'brand-zupona', '65W GaN Fast Charger', 'gan-fast-charger', 'ZUP-GAN-FAST-CHARGER', 'Small But Mighty', '65W in Your Pocket', 'active', 1499, 1999, 'BDT', 0, 0, 4.5, 156);
INSERT OR IGNORE INTO product_images (id, product_id, url, sort_order, is_primary) VALUES ('gan-fast-charger-img-1', 'gan-fast-charger', 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1200&q=85', 0, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('gan-fast-charger-v1', 'gan-fast-charger', 'ZUP-GAN-FAST-CHARGER-1', NULL, NULL, NULL, NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('gan-fast-charger-f1', 'gan-fast-charger', 'Zap', '65W Output', 0);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('gan-fast-charger-f2', 'gan-fast-charger', 'Package', 'Three Ports', 1);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('gan-fast-charger-f3', 'gan-fast-charger', 'ShieldCheck', 'GaN Cool Running', 2);

INSERT OR IGNORE INTO products (id, seller_id, category_id, brand_id, name, slug, sku, hero_headline, hero_subtitle, status, price, old_price, currency, is_featured, is_best_seller, rating_avg, rating_count) VALUES ('electric-kettle', NULL, 'home-appliances', 'brand-zupona', '1.8L Rapid Electric Kettle', 'electric-kettle', 'ZUP-ELECTRIC-KETTLE', 'Boil in Minutes', '1.8L Stainless', 'active', 1699, 2299, 'BDT', 0, 0, 4.4, 94);
INSERT OR IGNORE INTO product_images (id, product_id, url, sort_order, is_primary) VALUES ('electric-kettle-img-1', 'electric-kettle', 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1200&q=85', 0, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('electric-kettle-v1', 'electric-kettle', 'ZUP-ELECTRIC-KETTLE-1', NULL, NULL, NULL, NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('electric-kettle-f1', 'electric-kettle', 'Timer', 'Boils in 4 Min', 0);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('electric-kettle-f2', 'electric-kettle', 'ShieldCheck', 'Auto Shut-Off', 1);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('electric-kettle-f3', 'electric-kettle', 'Droplets', 'Stainless Interior', 2);

INSERT OR IGNORE INTO products (id, seller_id, category_id, brand_id, name, slug, sku, hero_headline, hero_subtitle, status, price, old_price, currency, is_featured, is_best_seller, rating_avg, rating_count) VALUES ('herbal-shower-gel-duo', NULL, 'bath-essentials', 'brand-glow-naturally', 'Herbal Shower Gel Duo', 'herbal-shower-gel-duo', 'ZUP-HERBAL-SHOWER-GEL-DUO', 'Fresh Every Morning', 'Two Bottle Pack', 'active', 699, 999, 'BDT', 0, 0, 4.4, 88);
INSERT OR IGNORE INTO product_images (id, product_id, url, sort_order, is_primary) VALUES ('herbal-shower-gel-duo-img-1', 'herbal-shower-gel-duo', 'https://images.unsplash.com/photo-1526947425960-945c6e72858f?auto=format&fit=crop&w=1200&q=85', 0, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('herbal-shower-gel-duo-v1', 'herbal-shower-gel-duo', 'ZUP-HERBAL-SHOWER-GEL-DUO-1', NULL, NULL, NULL, NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('herbal-shower-gel-duo-f1', 'herbal-shower-gel-duo', 'Leaf', 'Herbal Extracts', 0);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('herbal-shower-gel-duo-f2', 'herbal-shower-gel-duo', 'Droplets', 'pH Balanced', 1);

INSERT OR IGNORE INTO products (id, seller_id, category_id, brand_id, name, slug, sku, hero_headline, hero_subtitle, status, price, old_price, currency, is_featured, is_best_seller, rating_avg, rating_count) VALUES ('oud-musk-body-mist', NULL, 'fragrance', 'brand-glow-naturally', 'Oud Musk Body Mist', 'oud-musk-body-mist', 'ZUP-OUD-MUSK-BODY-MIST', 'Stay With Them', 'Long Lasting Oud', 'active', 799, 1199, 'BDT', 0, 0, 4.5, 117);
INSERT OR IGNORE INTO product_images (id, product_id, url, sort_order, is_primary) VALUES ('oud-musk-body-mist-img-1', 'oud-musk-body-mist', 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=1200&q=85', 0, 1);
INSERT OR IGNORE INTO product_variants (id, product_id, sku, option1_name, option1_value, swatch, price, old_price, stock_quantity, is_active) VALUES ('oud-musk-body-mist-v1', 'oud-musk-body-mist', 'ZUP-OUD-MUSK-BODY-MIST-1', NULL, NULL, NULL, NULL, NULL, 50, 1);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('oud-musk-body-mist-f1', 'oud-musk-body-mist', 'Sparkles', '8Hr Fragrance', 0);
INSERT OR IGNORE INTO product_features (id, product_id, icon, label, sort_order) VALUES ('oud-musk-body-mist-f2', 'oud-musk-body-mist', 'Wind', 'Light Alcohol Free', 1);

-- Baseline platform settings, editable later from an admin panel
INSERT OR IGNORE INTO site_settings (key, value) VALUES ('currency', 'BDT');
INSERT OR IGNORE INTO site_settings (key, value) VALUES ('currency_symbol', '৳');
INSERT OR IGNORE INTO site_settings (key, value) VALUES ('default_commission_rate', '10');
INSERT OR IGNORE INTO site_settings (key, value) VALUES ('points_per_taka', '0.02');
INSERT OR IGNORE INTO site_settings (key, value) VALUES ('free_shipping_threshold', '0');
INSERT OR IGNORE INTO site_settings (key, value) VALUES ('standard_shipping_fee', '80');
INSERT OR IGNORE INTO site_settings (key, value) VALUES ('express_shipping_fee', '120');
INSERT OR IGNORE INTO site_settings (key, value) VALUES ('seller_signup_open', '1');
INSERT OR IGNORE INTO site_settings (key, value) VALUES ('reviews_require_purchase', '0');
